// This file is generated by scripts/generate-assets.js.
// Run npm run generate-assets after adding or removing asset files.

export const outfitCategories = {
    background: [
            'assets/canvas/background/1.png', 'assets/canvas/background/2.png', 'assets/canvas/background/3.png', 'assets/canvas/background/4.png',
            'assets/canvas/background/5.png', 'assets/canvas/background/6.png', 'assets/canvas/background/7.png', 'assets/canvas/background/8.png',
            'assets/canvas/background/9.png', 'assets/canvas/background/10.png', 'assets/canvas/background/11.png', 'assets/canvas/background/12.png',
            'assets/canvas/background/13.png', 'assets/canvas/background/14.png', 'assets/canvas/background/15.png', 'assets/canvas/background/16.png',
            'assets/canvas/background/17.png', 'assets/canvas/background/18.png', 'assets/canvas/background/19.png', 'assets/canvas/background/20.png',
            'assets/canvas/background/21.png', 'assets/canvas/background/22.png', 'assets/canvas/background/23.png',
        ],
    body: {
        skin: [
                'assets/body/skin/1.png', 'assets/body/skin/2.png', 'assets/body/skin/3.png', 'assets/body/skin/4.png',
                'assets/body/skin/5.png', 'assets/body/skin/6.png', 'assets/body/skin/7.png', 'assets/body/skin/8.png',
                'assets/body/skin/9.png', 'assets/body/skin/10.png', 'assets/body/skin/11.png', 'assets/body/skin/12.png',
                'assets/body/skin/13.png', 'assets/body/skin/14.png', 'assets/body/skin/15.png', 'assets/body/skin/16.png',
                'assets/body/skin/17.png', 'assets/body/skin/18.png', 'assets/body/skin/19.png', 'assets/body/skin/20.png',
                'assets/body/skin/21.png', 'assets/body/skin/22.png', 'assets/body/skin/23.png', 'assets/body/skin/24.png',
                'assets/body/skin/25.png', 'assets/body/skin/26.png', 'assets/body/skin/27.png', 'assets/body/skin/28.png',
                'assets/body/skin/29.png',
            ],
        bodyDetails: [
                'assets/body/details/1.png', 'assets/body/details/2.png', 'assets/body/details/3.png',
            ],
    },
    face: {
        pupils: [
                'assets/face/pupils/1.png', 'assets/face/pupils/2.png', 'assets/face/pupils/3.png', 'assets/face/pupils/4.png',
                'assets/face/pupils/5.png', 'assets/face/pupils/6.png', 'assets/face/pupils/7.png', 'assets/face/pupils/8.png',
                'assets/face/pupils/9.png', 'assets/face/pupils/10.png', 'assets/face/pupils/11.png', 'assets/face/pupils/12.png',
                'assets/face/pupils/13.png', 'assets/face/pupils/14.png', 'assets/face/pupils/15.png',
            ],
        eyes: [
                'assets/face/eyes/1.png',
            ],
        eyelashes: [
                'assets/face/eyelashes/1.png', 'assets/face/eyelashes/2.png', 'assets/face/eyelashes/3.png', 'assets/face/eyelashes/4.png',
                'assets/face/eyelashes/5.png', 'assets/face/eyelashes/6.png', 'assets/face/eyelashes/7.png',
            ],
        eyebrows: [
                'assets/face/eyebrows/1.png', 'assets/face/eyebrows/2.png', 'assets/face/eyebrows/3.png', 'assets/face/eyebrows/4.png',
                'assets/face/eyebrows/5.png', 'assets/face/eyebrows/6.png', 'assets/face/eyebrows/7.png', 'assets/face/eyebrows/8.png',
                'assets/face/eyebrows/9.png', 'assets/face/eyebrows/10.png',
            ],
        nose: [
                'assets/face/nose/1.png', 'assets/face/nose/2.png', 'assets/face/nose/3.png', 'assets/face/nose/4.png',
                'assets/face/nose/5.png', 'assets/face/nose/6.png',
            ],
        mouth: [
                'assets/face/mouth/1.png', 'assets/face/mouth/2.png', 'assets/face/mouth/3.png', 'assets/face/mouth/4.png',
                'assets/face/mouth/5.png', 'assets/face/mouth/6.png', 'assets/face/mouth/7.png', 'assets/face/mouth/8.png',
                'assets/face/mouth/9.png', 'assets/face/mouth/10.png', 'assets/face/mouth/11.png', 'assets/face/mouth/12.png',
                'assets/face/mouth/13.png', 'assets/face/mouth/14.png',
            ],
        ears: [
                'assets/face/ears/1.png', 'assets/face/ears/2.png', 'assets/face/ears/3.png', 'assets/face/ears/4.png',
                'assets/face/ears/5.png', 'assets/face/ears/6.png', 'assets/face/ears/7.png', 'assets/face/ears/8.png',
            ],
        details: [
                'assets/face/details/1.png', 'assets/face/details/2.png', 'assets/face/details/3.png', 'assets/face/details/4.png',
                'assets/face/details/5.png', 'assets/face/details/6.png', 'assets/face/details/7.png', 'assets/face/details/8.png',
                'assets/face/details/9.png', 'assets/face/details/10.png', 'assets/face/details/11.png', 'assets/face/details/12.png',
                'assets/face/details/13.png', 'assets/face/details/14.png', 'assets/face/details/15.png', 'assets/face/details/16.png',
                'assets/face/details/17.png', 'assets/face/details/18.png', 'assets/face/details/19.png', 'assets/face/details/20.png',
                'assets/face/details/21.png',
            ],
    },
    clothes: {
        socks: [
                'assets/clothes/socks/1.png', 'assets/clothes/socks/2.png', 'assets/clothes/socks/3.png', 'assets/clothes/socks/6.png',
                'assets/clothes/socks/7.png', 'assets/clothes/socks/8.png', 'assets/clothes/socks/9.png', 'assets/clothes/socks/10.png',
            ],
        tops: [
                'assets/clothes/top/1.png', 'assets/clothes/top/1.webp', 'assets/clothes/top/2.webp', 'assets/clothes/top/3.png',
                'assets/clothes/top/3.webp', 'assets/clothes/top/4.png', 'assets/clothes/top/4.webp', 'assets/clothes/top/5.png',
                'assets/clothes/top/5.webp', 'assets/clothes/top/6.png', 'assets/clothes/top/6.webp', 'assets/clothes/top/7.png',
                'assets/clothes/top/7.webp', 'assets/clothes/top/8.png', 'assets/clothes/top/8.webp', 'assets/clothes/top/9.png',
                'assets/clothes/top/9.webp', 'assets/clothes/top/10.png', 'assets/clothes/top/10.webp', 'assets/clothes/top/11.webp',
                'assets/clothes/top/13.png', 'assets/clothes/top/13.webp', 'assets/clothes/top/14.png', 'assets/clothes/top/16.png',
                'assets/clothes/top/17.png', 'assets/clothes/top/18.png', 'assets/clothes/top/19.png', 'assets/clothes/top/20.png',
            ],
        dresses: [
                'assets/clothes/dress/1.png', 'assets/clothes/dress/1.webp', 'assets/clothes/dress/2.png', 'assets/clothes/dress/2.webp',
                'assets/clothes/dress/3.webp', 'assets/clothes/dress/4.webp', 'assets/clothes/dress/5.webp', 'assets/clothes/dress/6.webp',
                'assets/clothes/dress/7.webp', 'assets/clothes/dress/8.webp', 'assets/clothes/dress/9.webp', 'assets/clothes/dress/10.webp',
            ],
        jackets: [
                'assets/jacket/1.webp', 'assets/jacket/2.webp', 'assets/jacket/3.webp', 'assets/jacket/4.webp',
                'assets/jacket/5.webp', 'assets/jacket/6.webp', 'assets/jacket/7.webp', 'assets/jacket/8.webp',
                'assets/jacket/9.webp', 'assets/jacket/10.webp',
            ],
        bottoms: [
                'assets/clothes/bottom/1.png', 'assets/clothes/bottom/1.webp', 'assets/clothes/bottom/2.webp', 'assets/clothes/bottom/3.png',
                'assets/clothes/bottom/3.webp', 'assets/clothes/bottom/4.png', 'assets/clothes/bottom/4.webp', 'assets/clothes/bottom/5.png',
                'assets/clothes/bottom/5.webp', 'assets/clothes/bottom/6.png', 'assets/clothes/bottom/6.webp', 'assets/clothes/bottom/7.png',
                'assets/clothes/bottom/7.webp', 'assets/clothes/bottom/8.png', 'assets/clothes/bottom/9.png', 'assets/clothes/bottom/10.png',
                'assets/clothes/bottom/11.png', 'assets/clothes/bottom/12.png', 'assets/clothes/bottom/13.png',
            ],
        shoes: [
                'assets/clothes/shoes/1.png', 'assets/clothes/shoes/1.webp', 'assets/clothes/shoes/2.png', 'assets/clothes/shoes/2.webp',
                'assets/clothes/shoes/3.png', 'assets/clothes/shoes/3.webp', 'assets/clothes/shoes/4.png', 'assets/clothes/shoes/4.webp',
                'assets/clothes/shoes/5.png', 'assets/clothes/shoes/5.webp', 'assets/clothes/shoes/6.png', 'assets/clothes/shoes/6.webp',
                'assets/clothes/shoes/7.png', 'assets/clothes/shoes/7.webp', 'assets/clothes/shoes/8.png', 'assets/clothes/shoes/8.webp',
                'assets/clothes/shoes/9.png', 'assets/clothes/shoes/9.webp', 'assets/clothes/shoes/10.webp',
            ],
    },
    hair: {
        back: [
                'assets/hair/back/img1.webp', 'assets/hair/back/img2.webp', 'assets/hair/back/img3.webp', 'assets/hair/back/img4.webp',
                'assets/hair/back/img5.webp', 'assets/hair/back/img6.webp', 'assets/hair/back/img7.webp', 'assets/hair/back/img8.webp',
                'assets/hair/back/img9.webp', 'assets/hair/back/img11.webp', 'assets/hair/back/img12.webp', 'assets/hair/back/img13.webp',
                'assets/hair/back/img14.webp', 'assets/hair/back/img15.webp', 'assets/hair/back/img16.webp',
            ],
        bangs: [
                'assets/hair/bangs/1.webp', 'assets/hair/bangs/2.webp', 'assets/hair/bangs/3.webp', 'assets/hair/bangs/4.webp',
                'assets/hair/bangs/5.webp', 'assets/hair/bangs/6.webp', 'assets/hair/bangs/7.webp', 'assets/hair/bangs/8.webp',
                'assets/hair/bangs/9.webp', 'assets/hair/bangs/10.webp',
            ],
        color: [
                '#2b1b16', '#5b3527', '#8a5a3b', '#d0a064',
                '#f0d58a', '#c63f50', '#9b5bd3', '#4f8bd8',
            ],
    },
    accessories: {
        head: [
                'assets/body/horns/1.png', 'assets/body/horns/2.png', 'assets/body/horns/3.png', 'assets/body/horns/4.png',
            ],
        body: [
                'assets/accessories/body/1.png', 'assets/accessories/body/2.png', 'assets/accessories/body/3.png', 'assets/accessories/body/4.png',
                'assets/accessories/body/5.png', 'assets/accessories/body/6.png', 'assets/accessories/body/7.png', 'assets/accessories/body/8.png',
                'assets/accessories/body/9.png', 'assets/accessories/body/10.png', 'assets/accessories/body/11.png', 'assets/accessories/body/12.png',
                'assets/accessories/body/13.png', 'assets/accessories/body/14.png', 'assets/accessories/body/15.png', 'assets/accessories/body/16.png',
                'assets/accessories/body/17.png', 'assets/accessories/body/18.png', 'assets/accessories/body/19.png', 'assets/accessories/body/20.png',
                'assets/accessories/body/21.png', 'assets/accessories/body/22.png', 'assets/accessories/body/23.png', 'assets/accessories/body/24.png',
                'assets/accessories/body/25.png', 'assets/accessories/body/26.png', 'assets/accessories/body/27.png', 'assets/accessories/body/28.png',
                'assets/accessories/body/29.png', 'assets/accessories/body/30.png', 'assets/accessories/body/31.png', 'assets/accessories/body/32.png',
                'assets/accessories/body/33.png', 'assets/accessories/body/34.png', 'assets/accessories/body/35.png', 'assets/accessories/body/36.png',
                'assets/accessories/body/37.png', 'assets/accessories/body/38.png', 'assets/accessories/body/39.png', 'assets/accessories/body/40.png',
                'assets/accessories/body/41.png', 'assets/accessories/body/42.png', 'assets/accessories/body/ankle bracelet.webp', 'assets/accessories/body/bracelet.webp',
                'assets/accessories/body/bracelets.webp', 'assets/accessories/body/ear rings.webp', 'assets/accessories/body/long necklace.webp', 'assets/accessories/body/pearls ears.webp',
                'assets/accessories/body/pearls necklace.webp', 'assets/accessories/body/ring.webp', 'assets/accessories/body/small necklace.webp', 'assets/accessories/body/watch.webp',
            ],
        face: [
                'assets/accessories/face/1.png', 'assets/accessories/face/2.png', 'assets/accessories/face/3.png', 'assets/accessories/face/4.png',
                'assets/accessories/face/5.png', 'assets/accessories/face/6.png', 'assets/accessories/face/7.png', 'assets/accessories/face/8.png',
                'assets/accessories/face/9.png', 'assets/accessories/face/10.png', 'assets/accessories/face/11.png', 'assets/accessories/face/12.png',
                'assets/accessories/face/13.png', 'assets/accessories/face/14.png', 'assets/accessories/face/15.png', 'assets/accessories/face/16.png',
                'assets/accessories/face/17.png', 'assets/accessories/face/18.png', 'assets/accessories/face/19.png',
            ],
    },
    extras: {
        wings: [
                'assets/body/wings/1.png', 'assets/body/wings/2.png', 'assets/body/wings/3.png',
            ],
        tail: [
                'assets/body/tail/1.png', 'assets/body/tail/2.png', 'assets/body/tail/3.png', 'assets/body/tail/4.png',
                'assets/body/tail/5.png', 'assets/body/tail/6.png',
            ],
    },
    foreground: [
            'assets/canvas/foreground/1.png', 'assets/canvas/foreground/2.png', 'assets/canvas/foreground/3.png', 'assets/canvas/foreground/4.png',
            'assets/canvas/foreground/5.png', 'assets/canvas/foreground/6.png', 'assets/canvas/foreground/7.png', 'assets/canvas/foreground/8.png',
            'assets/canvas/foreground/9.png', 'assets/canvas/foreground/10.png',
        ],
};

export const skinColors = {
    'assets/body/skin/1.png': '#d4bdbd',
    'assets/body/skin/2.png': '#cca9a7',
    'assets/body/skin/3.png': '#bf8a86',
    'assets/body/skin/4.png': '#b37c73',
    'assets/body/skin/5.png': '#95635a',
    'assets/body/skin/6.png': '#673f39',
    'assets/body/skin/7.png': '#53312a',
    'assets/body/skin/8.png': '#33211d',
    'assets/body/skin/9.png': '#3c2c28',
    'assets/body/skin/10.png': '#5a3f38',
    'assets/body/skin/11.png': '#785b55',
    'assets/body/skin/12.png': '#764c33',
    'assets/body/skin/13.png': '#604235',
    'assets/body/skin/14.png': '#9d6e54',
    'assets/body/skin/15.png': '#8d6c5a',
    'assets/body/skin/16.png': '#b1846d',
    'assets/body/skin/17.png': '#d2a793',
    'assets/body/skin/18.png': '#d9ced1',
    'assets/body/skin/19.png': '#8d8384',
    'assets/body/skin/20.png': '#2f2a2b',
    'assets/body/skin/21.png': '#9d4c4d',
    'assets/body/skin/22.png': '#ce7e5d',
    'assets/body/skin/23.png': '#c89d6d',
    'assets/body/skin/24.png': '#758652',
    'assets/body/skin/25.png': '#95b6b2',
    'assets/body/skin/26.png': '#4d6b91',
    'assets/body/skin/27.png': '#776593',
    'assets/body/skin/28.png': '#b68cb0',
    'assets/body/skin/29.png': '#ca89a1',
};
