import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const assetsRoot = path.join(projectRoot, 'assets');
const outputPath = path.join(projectRoot, 'js', 'assets.js');

const imageExtensions = new Set(['.png', '.webp']);
const hairColors = ['#2b1b16', '#5b3527', '#8a5a3b', '#d0a064', '#f0d58a', '#c63f50', '#9b5bd3', '#4f8bd8'];

async function imagePaths(folder) {
    const dir = path.join(assetsRoot, folder);
    let entries;

    try {
        entries = await readdir(dir, { withFileTypes: true });
    } catch (error) {
        if (error.code === 'ENOENT') return [];
        throw error;
    }

    return entries
        .filter(entry => entry.isFile())
        .map(entry => entry.name)
        .filter(filename => imageExtensions.has(path.extname(filename).toLowerCase()))
        .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
        .map(filename => `assets/${folder}/${filename}`);
}

function formatArray(paths, indent = 8) {
    const spaces = ' '.repeat(indent);
    const lines = [];

    for (let i = 0; i < paths.length; i += 4) {
        lines.push(`${spaces}${paths.slice(i, i + 4).map(path => `'${path}'`).join(', ')},`);
    }

    return `[\n${lines.join('\n')}\n${' '.repeat(indent - 4)}]`;
}

async function readSkinColors() {
    const currentAssets = await readFile(outputPath, 'utf8');
    const match = currentAssets.match(/export const skinColors = \{[\s\S]*?\n\};/);
    return match?.[0] ?? 'export const skinColors = {};';
}

const categories = {
    background: await imagePaths('canvas/background'),
    body: {
        skin: await imagePaths('body/skin'),
        bodyDetails: await imagePaths('body/details'),
    },
    face: {
        pupils: await imagePaths('face/pupils'),
        eyes: await imagePaths('face/eyes'),
        eyelashes: await imagePaths('face/eyelashes'),
        eyebrows: await imagePaths('face/eyebrows'),
        nose: await imagePaths('face/nose'),
        mouth: await imagePaths('face/mouth'),
        ears: await imagePaths('face/ears'),
        details: await imagePaths('face/details'),
    },
    clothes: {
        socks: await imagePaths('clothes/socks'),
        tops: await imagePaths('clothes/top'),
        dresses: await imagePaths('clothes/dress'),
        jackets: await imagePaths('jacket'),
        bottoms: await imagePaths('clothes/bottom'),
        shoes: await imagePaths('clothes/shoes'),
    },
    hair: {
        back: await imagePaths('hair/back'),
        bangs: await imagePaths('hair/bangs'),
        color: hairColors,
    },
    accessories: {
        head: await imagePaths('body/horns'),
        body: await imagePaths('accessories/body'),
        face: await imagePaths('accessories/face'),
    },
    extras: {
        wings: await imagePaths('body/wings'),
        tail: await imagePaths('body/tail'),
    },
    weapons: await imagePaths('weapons'),
    foreground: await imagePaths('canvas/foreground'),
};

function formatValue(value, indent = 4) {
    if (Array.isArray(value)) return formatArray(value, indent + 4);

    const spaces = ' '.repeat(indent);
    const lines = Object.entries(value).map(([key, child]) => {
        return `${spaces}${key}: ${formatValue(child, indent + 4)},`;
    });

    return `{\n${lines.join('\n')}\n${' '.repeat(indent - 4)}}`;
}

const skinColors = await readSkinColors();
const content = `// This file is generated by scripts/generate-assets.js.\n// Run npm run generate-assets after adding or removing asset files.\n\nexport const outfitCategories = ${formatValue(categories)};\n\n${skinColors}\n`;

await writeFile(outputPath, content);
console.log(`Updated ${path.relative(projectRoot, outputPath)}`);
